apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-cs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxygen-cs
  template:
    metadata:
      labels:
        app: oxygen-cs
    spec:
      containers:
        - name: oxygen-cs-container
          image: jeredaco/oxygen-cs:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "150m"
              memory: "150Mi"