name: Upload Python Package

on:
  push:
    branches: '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Build package
        run: HOST=${{secrets.HOST}} TOKEN=${{secrets.TOKEN}} TICKETS=${{secrets.TICKETS}} T_MAX=${{secrets.T_MAX}} T_MIN=${{secrets.T_MIN}} DATABASE=${{secrets.DATABASE}} pipenv run start