name: Upload Python Package

on:
  push:
    branches: '**'

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv install --dev

      - name: Test with pytest
        run: |
          pipenv run test

      - name: Stop pipeline on test failure
        if: ${{ failure() }}
        run: exit 1

      - name: Linting with pylint
        run: |
          pipenv run lint

      - name: Formating with black
        run: |
          pipenv run format

      - name: Build Docker Image
        if: github.ref == 'refs/heads/feat/creation-image-docker-dans-le-pipeline'
        env:
          S_HOST: ${{secrets.HOST}}
          S_TOKEN: ${{secrets.TOKEN}}
          S_TICKET: ${{secrets.TICKETS}}
          S_T_MAX: ${{secrets.T_MAX}}
          S_T_MIN: ${{secrets.T_MIN}}
          S_DATABASE: ${{secrets.DATABASE}}
        run: docker build -t oxgen-cs:latest .
        #run: HOST=$S_HOST TOKEN=$S_TOKEN TICKETS=$S_TICKET T_MAX=$S_T_MAX T_MIN=$S_T_MIN DATABASE=$S_DATABASE pipenv run start